# 🛡️ Insurance Policy Management System
A demonstration of the **Policyholder**, **Product**, and **Payment** classes.  
Run each cell in order using **Shift + Enter**.

---

## 1. Import Classes

In [95]:
from policyholder import Policyholder
from product import Product
from payment import Payment
from csv_exporter import CSVExporter

print("✅ All classes imported successfully.")

✅ All classes imported successfully.

## 2. Create Insurance Products

In [63]:
health_plan = Product(
    product_id       = "P001",
    name             = "Family Health Plan",
    premium          = 150.00,
    coverage_details = "Covers hospitalization, outpatient care, and dental."
)

auto_plan = Product(
    product_id       = "P002",
    name             = "Comprehensive Auto Plan",
    premium          = 90.00,
    coverage_details = "Covers collision, theft, and third-party liability."
)

print("Products created:")
health_plan.display_details()
auto_plan.display_details()

Products created:
--------------------------------------------------
Product ID   : P001
Name         : Family Health Plan
Premium      : $150.00/month
Coverage     : Covers hospitalization, outpatient care, and dental.
Status       : Active
--------------------------------------------------
--------------------------------------------------
Product ID   : P002
Name         : Comprehensive Auto Plan
Premium      : $90.00/month
Coverage     : Covers collision, theft, and third-party liability.
Status       : Active
--------------------------------------------------

## 3. Update a Product

In [66]:
auto_plan.update(premium=95.00)
print("\nUpdated Auto Plan:")
auto_plan.display_details()

[PRODUCT UPDATED] 'Comprehensive Auto Plan' (ID: P002) details updated.

Updated Auto Plan:
--------------------------------------------------
Product ID   : P002
Name         : Comprehensive Auto Plan
Premium      : $95.00/month
Coverage     : Covers collision, theft, and third-party liability.
Status       : Active
--------------------------------------------------

## 4. Register Policyholders

In [69]:
holder1 = Policyholder("M001", "Amaka Obi",    "amaka.obi@example.com",  "555-1010")
holder2 = Policyholder("M002", "John Mensah",  "john.mensah@example.com","555-2020")

holder1.register()
holder2.register()

holder1.assign_product(health_plan)
holder2.assign_product(auto_plan)

[REGISTERED] Amaka Obi (ID: M001) is now Active.
[REGISTERED] John Mensah (ID: M002) is now Active.
[PRODUCT ASSIGNED] Amaka Obi subscribed to 'Family Health Plan'.
[PRODUCT ASSIGNED] John Mensah subscribed to 'Comprehensive Auto Plan'.

## 5. Process Payments

In [72]:
payment1 = Payment("PMT001", holder1, health_plan, health_plan.premium)
payment2 = Payment("PMT002", holder2, auto_plan,   auto_plan.premium)

# Holder 1 — pays in full
payment1.process_payment(150.00)

# Holder 2 — partial payment first
payment2.process_payment(50.00)

[PAYMENT PROCESSED] Amaka Obi paid $150.00 for 'Family Health Plan'. Status: Paid.
[PARTIAL PAYMENT] John Mensah paid $50.00. Remaining balance: $45.00.

## 6. Send a Payment Reminder

In [75]:
payment2.send_reminder()

# Holder 2 completes their payment
payment2.process_payment(45.00)

[REMINDER] Dear John Mensah, your payment of $45.00 for 'Comprehensive Auto Plan' is due.
[PAYMENT PROCESSED] John Mensah paid $45.00 for 'Comprehensive Auto Plan'. Status: Paid.

## 7. Apply a Late Payment Penalty

In [78]:
payment3 = Payment("PMT003", holder1, health_plan, health_plan.premium)
payment3.send_reminder()
payment3.apply_penalty()
payment3.process_payment(157.50)   # pays full amount including 5% penalty

[REMINDER] Dear Amaka Obi, your payment of $150.00 for 'Family Health Plan' is due.
[PENALTY APPLIED] Amaka Obi incurred a late penalty of $7.50. New amount due: $157.50.
[PAYMENT PROCESSED] Amaka Obi paid $157.50 for 'Family Health Plan'. Status: Paid.

## 8. Suspend & Reactivate a Policyholder

In [81]:
holder2.suspend()
holder2.reactivate()

[SUSPENDED] John Mensah (ID: M002) has been suspended.
[REACTIVATED] John Mensah (ID: M002) is now Active again.

## 9. Suspend a Product

In [84]:
auto_plan.suspend()
auto_plan.display_details()

[PRODUCT SUSPENDED] 'Comprehensive Auto Plan' (ID: P002) is no longer offered.
--------------------------------------------------
Product ID   : P002
Name         : Comprehensive Auto Plan
Premium      : $95.00/month
Coverage     : Covers collision, theft, and third-party liability.
Status       : Suspended
--------------------------------------------------

## 10. Display Final Account Details

In [87]:
print("\n" + "="*50)
print("ACCOUNT DETAILS — AMAKA OBI")
print("="*50)
holder1.display_details()

print("\n" + "="*50)
print("ACCOUNT DETAILS — JOHN MENSAH")
print("="*50)
holder2.display_details()

==================================================
ACCOUNT DETAILS — AMAKA OBI
==================================================
--------------------------------------------------
Policyholder ID : M001
Name            : Amaka Obi
Email           : amaka.obi@example.com
Phone           : 555-1010
Status          : Active
Registered On   : 2026-06-23
Product         : Family Health Plan
Payment History :
    Payment(ID=PMT001, Product=Family Health Plan, Due=$150.00, Paid=$150.00, Status=Paid, Date=2026-06-23)
    Payment(ID=PMT003, Product=Family Health Plan, Due=$157.50, Paid=$157.50, Status=Paid, Date=2026-06-23)
--------------------------------------------------

==================================================
ACCOUNT DETAILS — JOHN MENSAH
==================================================
--------------------------------------------------
Policyholder ID : M002
Name            : John Mensah
Email           : john.mensah@example.com
Phone           : 555-2020
Status          : Active
Registered On   : 2026-06-23
Product         : Comprehensive Auto Plan
Payment History :
    Payment(ID=PMT002, Product=Comprehensive Auto Plan, Due=$95.00, Paid=$95.00, Status=Paid, Date=2026-06-23)
--------------------------------------------------

## 11. Export Data to CSV
Running this cell saves three CSV files in the same folder as this notebook.

In [90]:
all_policyholders = [holder1, holder2]
all_products      = [health_plan, auto_plan]

ph_file  = CSVExporter.export_policyholders(all_policyholders)
pr_file  = CSVExporter.export_products(all_products)
pay_file = CSVExporter.export_payments(all_policyholders)

[EXPORT] Policyholders exported to 'policyholders_20260623_221112.csv'.
[EXPORT] Products exported to 'products_20260623_221112.csv'.
[EXPORT] Payments exported to 'payments_20260623_221112.csv'.

## 12. Preview Exported CSVs with pandas

In [93]:
import pandas as pd

print("── Policyholders ──")
display(pd.read_csv(ph_file))

print("\n── Products ──")
display(pd.read_csv(pr_file))

print("\n── Payments ──")
display(pd.read_csv(pay_file))

── Policyholders ──

,Member ID,Name,Email,Phone,Status,Registered On,Product
0,M001,Amaka Obi,amaka.obi@example.com,555-1010,Active,2026-06-23,Family Health Plan
1,M002,John Mensah,john.mensah@example.com,555-2020,Active,2026-06-23,Comprehensive Auto Plan

── Products ──

,Product ID,Name,Premium ($/month),Coverage Details,Status
0,P001,Family Health Plan,150.0,"Covers hospitalization, outpatient care, and d...",Active
1,P002,Comprehensive Auto Plan,95.0,"Covers collision, theft, and third-party liabi...",Suspended

── Payments ──

,Payment ID,Policyholder ID,Policyholder Name,Product,Amount Due ($),Amount Paid ($),Status,Date Paid
0,PMT001,M001,Amaka Obi,Family Health Plan,150.0,150.0,Paid,2026-06-23
1,PMT003,M001,Amaka Obi,Family Health Plan,157.5,157.5,Paid,2026-06-23
2,PMT002,M002,John Mensah,Comprehensive Auto Plan,95.0,95.0,Paid,2026-06-23